import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter02/dataclass/dataclass.dart';
import 'package:flutter02/infomation.dart';


class Listview extends StatefulWidget {
  const Listview({Key? key}) : super(key: key);

  @override
  State<Listview> createState() => _ListviewState();
}

class _ListviewState extends State<Listview> {
  List<Autogenerated> b = [];
  int a = 1;
  List<Widget> widgets = [];
  @override
  void initState() {
    super.initState();
    readdata();
  }

  Future<void> readdata() async {
    String url = 'https://pasutara.dgr.go.th/api_well/api/FindWellAll?fbclid=IwAR0z-Jl159YfkCbTmktf5XT_wDS3cdozZAMTKhihcTLqfngWVSbf0qS1Q8g';
    Response response = await Dio().get(url);
    int index01 = 0;
    for (var sna in response.data) {
      Map<String, dynamic> map = sna;
      Autogenerated model = Autogenerated.fromJson(map);

      setState(() {
        b.add(model);
        widgets.add(crtwidget(model, index01));
      });
      index01++;
    }
  }

  Widget crtwidget(Autogenerated h2, int index01) => GestureDetector(
        child: Card(
          child: Center(
              child: Column(
            children: [
              ListTile(
                onTap: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => Infomation(
                        h2:b[index01],
                      ),
                    ),
                  );
                },
                leading: const Icon(Icons.man_sharp),
                title: Text(
                  h2.firstPageUrl.toString(),
                  style: TextStyle(
                      color:
                          const Color.fromARGB(255, 5, 69, 2).withOpacity(0.9),
                      fontSize: 20),
                ),
                tileColor: const Color.fromARGB(175, 187, 236, 179),
                subtitle: Text(
                  h2.lastPageUrl.toString(),
                  style: TextStyle(
                      color:
                          const Color.fromARGB(140, 207, 6, 6).withOpacity(0.9),
                      fontSize: 20),
                ),
              )
            ],
          )),
        ),
      );
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
            gradient: RadialGradient(
                center: Alignment(0, -0.33),
                radius: 2,
                colors: <Color>[
              Color.fromARGB(255, 172, 250, 148),
              Color.fromARGB(255, 46, 122, 254)
            ])),
        child:widgets.isEmpty
            ? const Center(
                child: CircularProgressIndicator(),
              )
            : ListView(
                children : widgets
              ),
      ),
    );
  }
}
